services:
  yafa-pwa-staging:
    container_name: yafa-pwa-staging
    image: ghcr.io/jthies73/yafa-pwa:staging
    volumes:
      - /usr/share/nginx/html/jthies73.html:/usr/share/nginx/html/jthies73.html:ro

networks:
  default:
    name: web_proxy
    external: true
