server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    location ~ ^/jthies73/?$ {
        try_files /jthies73.html =404;
    }

    # Fallback to index.html for Vue Router history mode
    location / {
        try_files $uri $uri/ /index.html;
    }
}
